# Generated by Django 5.2.15 on 2026-06-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loteria", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registroloteria",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Registro de Lotería",
                "verbose_name_plural": "Registros de Lotería",
            },
        ),
        migrations.AlterField(
            model_name="registroloteria",
            name="fecha",
            field=models.DateField(unique=True, verbose_name="Fecha del Sorteo"),
        ),
    ]
